on: [push]

name: Tests

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      run: apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
